- pom.xml
- src/main/java/org/mifos/connector/ams/interop/ClientResponseProcessor.java
- src/main/java/org/mifos/connector/ams/interop/InteropPartyResponseProcessor.java
- src/main/java/org/mifos/connector/ams/interop/QuoteResponseProcessor.java
- src/main/java/org/mifos/connector/ams/interop/TransfersResponseProcessor.java
- src/main/java/org/mifos/connector/ams/zeebe/ZeebeClientConfiguration.java
- src/main/java/org/mifos/connector/ams/zeebe/ZeebeeWorkers.java
- src/main/resources/application-fin12.yml
- src/main/resources/application.yml
PR consists of required changes for Zeebe v1.1.0 portability.
> Zeebe v1.1.0 Upgrade

- src/main/java/org/mifos/connector/ams/interop/ClientResponseProcessor.java
- src/main/java/org/mifos/connector/ams/interop/InteroperationRouteBuilder.java
- src/main/java/org/mifos/connector/ams/interop/TransfersResponseProcessor.java
*Changes*
1. Parsed error from API into `JsonObject`.
2. Map the `errorInformation` Zeebe variable to `JsonObject`.
> Errors from API added in zeebe variable

- .gitignore
- src/main/java/org/mifos/connector/ams/zeebe/ZeebeeWorkers.java
- src/main/resources/application-bb.yml
Removing unecessary tenant conditions and updating logic
> Removing unecessary tenant conditions and updating logic

- build.gradle
- src/main/java/org/mifos/connector/ams/interop/AmsCommonService.java
- src/main/java/org/mifos/connector/ams/interop/AmsService.java
- src/main/java/org/mifos/connector/ams/interop/InteroperationRouteBuilder.java
- src/main/java/org/mifos/connector/ams/interop/PrepareTransferRequest.java
- src/main/java/org/mifos/connector/ams/zeebe/ZeebeUtil.java
- src/main/java/org/mifos/connector/ams/zeebe/ZeebeVariables.java
- src/main/java/org/mifos/connector/ams/zeebe/ZeebeeWorkers.java
- src/main/resources/application-bb.yml
- src/main/resources/application-fin12.yml
- src/main/resources/application.yml
- src/main/resources/endpoints.xml
- added account identifier worker 
- Utlity function from gsma transfer to transaction channel dto
@avikganguly01 @fynmanoj 
addressed review comments :
- merged into single commit
- changed logger level to debug
- Changed date format to take from generated date
- Refactored logic to extract account no and identifier
- changed application yaml level properties as mentioned
> Account Identifier Worker

- src/main/java/org/mifos/connector/ams/zeebe/ZeebeeWorkers.java
[PHEE-218](https://fynarfin.atlassian.net/browse/PHEE-218?atlOrigin=eyJpIjoiNTIyMjFjZTliNDMzNDdkMWI3YTE0NDU3MTRiNzAyODIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ0)
[PHEE-218]: https://fynarfin.atlassian.net/browse/PHEE-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PHEE-218 payee-commit-transfer worker fixed

- src/main/java/org/mifos/connector/ams/zeebe/workers/accountdetails/AmsCreditorWorker.java
- src/main/java/org/mifos/connector/ams/zeebe/workers/accountdetails/AmsDataTableQueryResponse.java
The following changes are required to generate coverage cert.
> NEOB-1083 add internalAccountId to the variables

- build.gradle
[PHEE-347 update Jfrog URLs in all paymenthub repos](https://github.com/openMF/ph-ee-operations-app/pull/52)
>  PHEE-347 update Jfrog URLs in all paymenthub repos

- .circleci/config.yml
* Added CircleCI to build and push the docker image to docker hub
* Add a link to the design document or include the design bullet points related to this PR here.
> #GOV-527 Build and Push the Docker image to DockerHub

- .circleci/config.yml
(https://mifosforge.jira.com/browse/GOV-527)
* Added CircleCI config yaml to .circelci folder.
* CircieCI to build and push docker image to dockerhub upon github tag release and latest.
* (https://mifosforge.jira.com/browse/GOV-527)
> #GOV-527 Build and Push Docker Image to Dockerhub

- .circleci/config.yml
- build.gradle
Changed the pipeline for openjdk v13
https://fynarfin.atlassian.net/browse/PHEE-377?atlOrigin=eyJpIjoiM2RlYzIxODRkOGNkNGYzZTkwNDZjY2MyNTc4ODRmZWYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
> [PHEE-377] jdk version update

- build.gradle
- src/main/java/org/mifos/connector/AmsConnectorApplication.java
- src/main/java/org/mifos/connector/ams/camel/config/CamelProperties.java
- src/main/java/org/mifos/connector/ams/errorhandler/ErrorTranslator.java
- src/main/java/org/mifos/connector/ams/interop/AmsCommonService.java
- src/main/java/org/mifos/connector/ams/interop/AmsService.java
- src/main/java/org/mifos/connector/ams/interop/ErrorParserRouteBuilder.java
- src/main/java/org/mifos/connector/ams/interop/InteroperationRouteBuilder.java
- src/main/java/org/mifos/connector/ams/interop/TransfersResponseProcessor.java
- src/main/java/org/mifos/connector/ams/zeebe/ZeebeVariables.java
- src/main/java/org/mifos/connector/ams/zeebe/ZeebeeWorkers.java
- src/main/resources/application.yml
[PHEE-440 Create a worker to send the callback in ams_mifos](https://fynarfin.atlassian.net/browse/PHEE-440?atlOrigin=eyJpIjoiMWNkZTc0MTdkYmQ3NGZmNGI5YTBlZDQ1Nzg2MTZjZjEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-440 Create a worker to send the callback in ams_mifos

- .circleci/config.yml
- build.gradle
* [PHEE-455 Fix AMS mifos startup issue](https://fynarfin.atlassian.net/browse/PHEE-455?atlOrigin=eyJpIjoiMWY3MTQxOTczYWMwNGFlZmIyMTI4N2ZiZmUxZDYxMmUiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-455 Fix AMS mifos startup issue

- build.gradle
- src/main/resources/application.yml
(https://mifosforge.jira.com/browse/GOV-134) 
* Added Liveness and readiness probes to Application yaml
* Added actuators dependency in gradle file
> #GOV-134 enable liveness and readiness

- src/main/resources/application-bb.yml
[PHEE-482 Update fspids in ams mifos](https://fynarfin.atlassian.net/browse/PHEE-482?atlOrigin=eyJpIjoiY2E5YzA0YzBlOTM0NDc3ZGI4M2I5MzA3ZjY0OTM4YTgiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> PHEE-482 Update fspids in ams mifos

- build.gradle
* Fixing the liveness and readiness build issue with dependencies
* [GOV-134 Requires the Payment Building Block to degrade gracefully under cond…](https://mifosforge.jira.com/browse/GOV-134?atlOrigin=eyJpIjoiYjMyMDVlOTczYjVmNDYyNGI0MWRjZjQ1NWNkMmFkZDAiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [GOV-134] Fix liveness and readiness build issues

- build.gradle
- src/main/java/org/mifos/connector/ams/zeebe/ZeebeClientConfiguration.java
- src/main/resources/application.yml
[PHEE-560 Reduce Memory Consumption of 6 reported services](https://fynarfin.atlassian.net/browse/PHEE-560?atlOrigin=eyJpIjoiZTY2NzcwNWJhMWViNDE0OTk2ODdjNmU0NTliNmRmOTIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-560] Reduce Memory Consumption of reported services

- src/main/resources/application.yml
* PR title should have jira ticket enclosed in `[]`.<br>
Format: ``` [jira_ticket] description```<br>
ex: [phee-123] PR title.
* Add a link to the Jira ticket.
* Describe the changes made and why they were made.
> [GOV-134] Enable the health endpoint for Spring Boot Actuator configuration

- src/main/java/org/mifos/connector/ams/zeebe/workers/accountdetails/GetAccountDetailsFromAmsWorker.java
- src/main/java/org/mifos/connector/ams/zeebe/workers/bookamount/MoneyInOutWorker.java
* PR title should have jira ticket enclosed in `[]`.<br>
Format: ``` [jira_ticket] description```<br>
ex: [phee-123] PR title.
* Add a link to the Jira ticket.
* Describe the changes made and why they were made.
> add recovery for batch request and generic error handling on get details

- src/main/java/org/mifos/connector/ams/zeebe/workers/bookamount/TransferToConversionAccountInAmsWorker.java
* PR title should have jira ticket enclosed in `[]`.<br>
Format: ``` [jira_ticket] description```<br>
ex: [phee-123] PR title.
* Add a link to the Jira ticket.
* Describe the changes made and why they were made.
> BCB-3503 change jsonPath to represent the fineract change

- src/main/java/org/mifos/connector/ams/interop/AmsCommonService.java
- src/main/java/org/mifos/connector/ams/zeebe/ZeebeVariables.java
- src/main/java/org/mifos/connector/ams/zeebe/ZeebeeWorkers.java
[PHEE-721 Fix /gsma/transcation API to work with different dfspids.](https://fynarfin.atlassian.net/browse/PHEE-721?atlOrigin=eyJpIjoiZTZkMjIwNGU1ODJkNDFjMWFjOTE3YzYwZDdlOTgzZjciLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
> [PHEE-721] Fix /gsma/transcation API to work with different dfspids.
